module Lyric.Cli.Tests.NugetShimTests

open System
open System.IO
open Expecto
open Lyric.Cli.NugetShim

/// Find a real `.dll` on disk we can reflect over.  The Lyric.Lexer
/// assembly always exists adjacent to the test runner — it ships
/// from `compiler/src/Lyric.Lexer` and provides a stable, in-tree
/// surface to exercise the generator without depending on any
/// out-of-tree NuGet restore.
let private locateProbeDll () : string =
    let candidates =
        [ Path.Combine(AppContext.BaseDirectory, "Lyric.Lexer.dll")
          Path.Combine(AppContext.BaseDirectory, "Lyric.Stdlib.dll") ]
    match candidates |> List.tryFind File.Exists with
    | Some p -> p
    | None ->
        failwithf "no probe DLL on disk; looked at: %A" candidates

let tests =
    testList "Lyric.Cli.NugetShim" [

        testCase "lyric package name from nuget id" <| fun () ->
            Expect.equal (lyricNameFromNugetId "System.Text.Json")
                "SystemTextJson" "dots dropped"
            Expect.equal (lyricNameFromNugetId "Newtonsoft.Json")
                "NewtonsoftJson" "preserves casing"
            Expect.equal (lyricNameFromNugetId "polly")
                "Polly" "lowercase head capitalised"
            Expect.equal (lyricNameFromNugetId "Polly")
                "Polly" "already-capital head untouched"

        testCase "missing dll surfaces ShimDllMissing" <| fun () ->
            match generate "/nope/does/not/exist.dll" "X" "1.0.0" [] with
            | Error (ShimDllMissing p) ->
                Expect.stringContains p "exist.dll" "path surfaces"
            | other -> failwithf "expected ShimDllMissing, got %A" other

        testCase "shim header carries axiom + package + autogen banner" <| fun () ->
            let dll = locateProbeDll ()
            match generate dll "Probe.Pkg" "1.2.3" [] with
            | Error e -> failwithf "generate failed: %s" (renderShimError e)
            | Ok shim ->
                Expect.stringContains shim.LyricSource
                    "@axiom(\"from NuGet package Probe.Pkg v1.2.3\")"
                    "axiom carries id + version"
                Expect.stringContains shim.LyricSource
                    "package ProbePkg"
                    "package name derives from NuGet id"
                Expect.stringContains shim.LyricSource
                    "Auto-generated by `lyric restore`"
                    "warning banner present"

        testCase "extern type lines are sorted by full name" <| fun () ->
            let dll = locateProbeDll ()
            match generate dll "Probe" "0.1.0" [] with
            | Error e -> failwithf "generate failed: %s" (renderShimError e)
            | Ok shim ->
                let externLines =
                    shim.LyricSource.Split('\n')
                    |> Array.filter (fun l -> l.StartsWith("extern type "))
                    |> Array.toList
                Expect.isGreaterThan externLines.Length 0
                    "at least one extern type emitted"
                let sorted = List.sort externLines
                Expect.equal externLines sorted
                    "extern type lines come out sorted"

        testCase "skip report only present when something was skipped" <| fun () ->
            let dll = locateProbeDll ()
            match generate dll "Probe" "0.1.0" [] with
            | Error e -> failwithf "generate failed: %s" (renderShimError e)
            | Ok shim ->
                // Lyric.Lexer / Lyric.Stdlib are guaranteed to have
                // *some* skipped surface (e.g. methods on F#'s union
                // types take complex parameters), so the report
                // should be Some.
                Expect.isSome shim.SkipReport
                    "expected at least some skipped methods on a real DLL"
                let report = shim.SkipReport.Value
                Expect.stringContains report "Skipped surface for Probe v0.1.0"
                    "skip report header"

        testCase "exported counts non-zero on a real assembly" <| fun () ->
            let dll = locateProbeDll ()
            match generate dll "Probe" "0.1.0" [] with
            | Error e -> failwithf "generate failed: %s" (renderShimError e)
            | Ok shim ->
                Expect.isGreaterThan shim.ExternTypes 0
                    "at least one extern type"
                // Methods may be zero when every method has unsupported
                // sig (private, generic, complex types), so don't
                // assert > 0; just check it's non-negative.
                Expect.isGreaterThanOrEqual shim.ExternMethods 0
                    "method count non-negative"
    ]
