module Lyric.Emitter.Tests.Program

open Expecto

[<EntryPoint>]
let main argv =
    let allTests =
        testList "Lyric.Emitter" [
            StdlibSmokeTests.tests
            EmitterScaffoldTests.tests
            HelloWorldTests.tests
            ArithmeticTests.tests
            ControlFlowTests.tests
            FunctionCallTests.tests
            RecordTests.tests
            SliceTests.tests
            EnumMatchTests.tests
            UnionTests.tests
            InterfaceTests.tests
            ContractTests.tests
            GenericsTests.tests
            AsyncTests.tests
            BankingSmokeTests.tests
            StdlibSeedTests.tests
            DelegateTests.tests
            DistinctTypeTests.tests
            OpaqueTypeTests.tests
            MultiPackageTests.tests
            CrossAssemblyGenericTests.tests
            WhereClauseTests.tests
            NullaryInferenceTests.tests
            GenericUnionTests.tests
            SyntaxSimplificationTests.tests
            BclDispatchTests.tests
            ParseTests.tests
            DeferTests.tests
            StdlibImportTests.tests
            NegativePatternTests.tests
            PatternMatchingTests.tests
            InlineMethodTests.tests
            EndToEndSmokeTests.tests
            BuiltinTests.tests
            StdFileTests.tests
            CollectionTests.tests
            OutParamTests.tests
            IterTests.tests
            StubbableTests.tests
            AliasTests.tests
            AutoFfiTests.tests
            StdTimeTests.tests
            WireTests.tests
            GenericRecordTests.tests
            JsonDeriveTests.tests
            ContractMetaTests.tests
            TryCatchTests.tests
            StdHttpTests.tests
            StdMathTests.tests
            StdRandomTests.tests
            SnapshotTestingTests.tests
            PropertyTestingTests.tests
            CancellationTests.tests
            StructuredConcurrencyTests.tests
            AsyncLocalTests.tests
            MockingTests.tests
            RestoredPackageE2ETests.tests
            ProtectedTypeTests.tests
            StdlibLyricTests.tests
            KernelBoundaryTests.tests
            JvmSelfTest.tests
            JvmLoweringTest.tests
            JvmLoweringB4Test.tests
            JvmLoweringB5Test.tests
            JvmLoweringB6Test.tests
            JvmLoweringB7Test.tests
            JvmLoweringB8Test.tests
            JvmLoweringB9Test.tests
            JvmLoweringB10Test.tests
            JvmLoweringB11Test.tests
            JvmLoweringB12Test.tests
            JvmLoweringB13Test.tests
            JvmLoweringB14Test.tests
            JvmLoweringB15Test.tests
            JvmLoweringB16Test.tests
            JvmLoweringB17Test.tests
            JvmLoweringB18Test.tests
            JvmLoweringB19Test.tests
            JvmLoweringB20Test.tests
            JvmLoweringB21Test.tests
            JvmLoweringB22Test.tests
            JvmLoweringB23Test.tests
            JvmLoweringB24Test.tests
            JvmLoweringB25Test.tests
            JvmLoweringB26Test.tests
            JvmLoweringB27Test.tests
            JvmLoweringB28Test.tests
            JvmLoweringB29Test.tests
            JvmLoweringB30Test.tests
            JvmLoweringB31Test.tests
            JvmLoweringB32Test.tests
            JvmLoweringB33Test.tests
            JvmLoweringB34Test.tests
            JvmLoweringB35Test.tests
            JvmLoweringB36Test.tests
            JvmLoweringB37Test.tests
            JvmLoweringB38Test.tests
            JvmLoweringB39Test.tests
            JvmLoweringB40Test.tests
            JvmLoweringB41Test.tests
            JvmLoweringB42Test.tests
            JvmLoweringB43Test.tests
            JvmLoweringB44Test.tests
            JvmLoweringB45Test.tests
            JvmLoweringB46Test.tests
            JvmLoweringB47Test.tests
            JvmLoweringB48Test.tests
            JvmLoweringB49Test.tests
            JvmLoweringB50Test.tests
            JvmLoweringB51Test.tests
            JvmLoweringB52Test.tests
            JvmLoweringB53Test.tests
            JvmLoweringB54Test.tests
            JvmLoweringB55Test.tests
            JvmLoweringB56Test.tests
            JvmLoweringB57Test.tests
            JvmLoweringB58Test.tests
            JvmLoweringB59Test.tests
            JvmLoweringB60Test.tests
            JvmLoweringB61Test.tests
            SelfHostedLexerTests.tests
            MultiFilePackageTests.tests
        ]
    runTestsWithCLIArgs [] argv allTests
