// Generates lyric-ui/src/host_assets.l from the compiled runtime (dist/) and
// ui.css, so a Lyric application serves the host runtime from memory with no
// files to deploy.
//
//   node embed.mjs          regenerate
//   node embed.mjs --check  exit 1 if host_assets.l is out of date (CI)
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "host_assets.l");

const assets = [
  ["runtimeMainJs", "dist/main.js"],
  ["runtimeTreeJs", "dist/tree.js"],
  ["runtimeRenderJs", "dist/render.js"],
  ["themeCss", "ui.css"],
];

const DELIM = "#####";

function literal(name, text) {
  if (text.includes(`"${DELIM}`)) {
    throw new Error(`${name}: content contains the raw-string delimiter`);
  }
  return `pub val ${name}: String = r${DELIM}"${text}"${DELIM}\n`;
}

const parts = assets.map(([name, file]) => {
  const text = readFileSync(join(here, file), "utf8");
  return { name, file, text };
});
const digest = createHash("sha256").update(parts.map((p) => p.text).join("\0")).digest("hex").slice(0, 16);

let src = `//! Ui.Host.Assets — the browser host runtime and default theme, embedded
//! (docs/65-ui-library-sketch.md §10.3).
//!
//! GENERATED by lyric-ui/runtime/embed.mjs from lyric-ui/runtime/dist/*.js
//! and lyric-ui/runtime/ui.css — do not edit.  Regenerate with
//! \`npm run build && node embed.mjs\` in lyric-ui/runtime/.
@runtime_checked
package Ui.Host.Assets

/// Content digest of the embedded assets, used as a cache-busting version.
pub val assetVersion: String = "${digest}"

`;
for (const p of parts) {
  src += `/// ${p.file}\n` + literal(p.name, p.text) + "\n";
}

if (process.argv.includes("--check")) {
  const current = readFileSync(out, "utf8");
  if (current !== src) {
    console.error("host_assets.l is out of date; run `npm run build && node embed.mjs` in lyric-ui/runtime/");
    process.exit(1);
  }
} else {
  writeFileSync(out, src);
}
