module Lyric.Emitter.Tests.Program

open Expecto

[<EntryPoint>]
let main argv =
    let allTests =
        testList "Lyric.Emitter" [
            EmitterScaffoldTests.tests
            HelloWorldTests.tests
            ArithmeticTests.tests
            ControlFlowTests.tests
            FunctionCallTests.tests
            RecordTests.tests
            SliceTests.tests
            EnumMatchTests.tests
            UnionTests.tests
            InterfaceTests.tests
            ImplBlockGenericsTests.tests
            ContractTests.tests
            GenericsTests.tests
            AsyncTests.tests
            BankingSmokeTests.tests
            StdlibSeedTests.tests
            DelegateTests.tests
            DistinctTypeTests.tests
            OpaqueTypeTests.tests
            MultiPackageTests.tests
            CrossAssemblyGenericTests.tests
            WhereClauseTests.tests
            NullaryInferenceTests.tests
            GenericUnionTests.tests
            SyntaxSimplificationTests.tests
            BclDispatchTests.tests
            DeferTests.tests
            StdlibImportTests.tests
            NegativePatternTests.tests
            PatternMatchingTests.tests
            InlineMethodTests.tests
            EndToEndSmokeTests.tests
            BuiltinTests.tests
            StdFileTests.tests
            CollectionTests.tests
            OutParamTests.tests
            IterTests.tests
            StubbableTests.tests
            AliasTests.tests
            AutoFfiTests.tests
            StdTimeTests.tests
            WireTests.tests
            GenericRecordTests.tests
            JsonDeriveTests.tests
            ContractMetaTests.tests
            SdkVersionSkewTests.tests
            TryCatchTests.tests
            StdHttpTests.tests
            StdMathTests.tests
            StdRandomTests.tests
            SnapshotTestingTests.tests
            PropertyTestingTests.tests
            CancellationTests.tests
            StructuredConcurrencyTests.tests
            AsyncLocalTests.tests
            MockingTests.tests
            RestoredPackageE2ETests.tests
            ProtectedTypeTests.tests
            StdlibLyricTests.tests
            KernelBoundaryTests.tests
            JvmSelfTest.tests
            MsilSelfTestM1.tests
            MsilSelfTestM2a.tests
            MsilSelfTestM2b.tests
            MsilSelfTestM2c.tests
            MsilSelfTestM2d.tests
            MsilSelfTestM3.tests
            MsilSelfTestM4.tests
            MsilSelfTestM5.tests
            MsilSelfTestM6.tests
            MsilSelfTestM7.tests
            MsilSelfTestM8.tests
            MsilSelfTestM9.tests
            MsilSelfTestM10.tests
            MsilSelfTestM11.tests
            MsilSelfTestM12.tests
            MsilSelfTestM13.tests
            MsilSelfTestM14.tests
            MsilSelfTestM15.tests
            MsilSelfTestM16.tests
            MsilSelfTestM17.tests
            MsilSelfTestM18.tests
            MsilSelfTestM19.tests
            MsilSelfTestM20.tests
            MsilSelfTestM21.tests
            MsilSelfTestM22.tests
            MsilSelfTestM23.tests
            MsilSelfTestM24.tests
            MsilSelfTestM25.tests
            MsilSelfTestM26.tests
            MsilSelfTestM27.tests
            MsilSelfTestM28.tests
            MsilSelfTestM29.tests
            MsilSelfTestM30.tests
            MsilSelfTestM31.tests
            MsilSelfTestM32.tests
            MsilSelfTestM33.tests
            MsilSelfTestM34.tests
            MsilSelfTestM35.tests
            MsilSelfTestM36.tests
            MsilSelfTestM37.tests
            MsilSelfTestM38.tests
            MsilSelfTestM39.tests
            MsilSelfTestM40.tests
            MsilSelfTestM41.tests
            MsilSelfTestM42.tests
            MsilSelfTestM43.tests
            MsilSelfTestM44.tests
            MsilSelfTestM45.tests
            MsilSelfTestM46.tests
            MsilSelfTestM47.tests
            MsilSelfTestM48.tests
            MsilSelfTestM49.tests
            MsilSelfTestM50.tests
            MsilSelfTestM51.tests
            MsilSelfTestM52.tests
            MsilSelfTestM53.tests
            MsilSelfTestM54.tests
            MsilSelfTestM55.tests
            MsilSelfTestM56.tests
            MsilSelfTestM57.tests
            MsilSelfTestM58.tests
            MsilSelfTestM59.tests
            MsilSelfTestM60.tests
            MsilSelfTestM61.tests
            MsilSelfTestM62.tests
            MsilSelfTestM63.tests
            MsilSelfTestM64.tests
            MsilSelfTestM65.tests
            MsilSelfTestM66.tests
            MsilSelfTestM67.tests
            MsilSelfTestM68.tests
            MsilSelfTestM69.tests
            MsilSelfTestM70.tests
            MsilSelfTestM71.tests
            MsilSelfTestM72.tests
            MsilSelfTestM73.tests
            MsilSelfTestM74.tests
            MsilSelfTestM75.tests
            MsilSelfTestM76.tests
            MsilSelfTestM77.tests
            MsilSelfTestM78.tests
            MsilSelfTestM79.tests
            MsilSelfTestM80.tests
            MsilSelfTestM81.tests
            MsilSelfTestM82.tests
            MsilSelfTestM83.tests
            JvmLoweringTest.tests
            JvmLoweringB4Test.tests
            JvmLoweringB5Test.tests
            JvmLoweringB6Test.tests
            JvmLoweringB7Test.tests
            JvmLoweringB8Test.tests
            JvmLoweringB9Test.tests
            JvmLoweringB10Test.tests
            JvmLoweringB11Test.tests
            JvmLoweringB12Test.tests
            JvmLoweringB13Test.tests
            JvmLoweringB14Test.tests
            JvmLoweringB15Test.tests
            JvmLoweringB16Test.tests
            JvmLoweringB17Test.tests
            JvmLoweringB18Test.tests
            JvmLoweringB19Test.tests
            JvmLoweringB20Test.tests
            JvmLoweringB21Test.tests
            JvmLoweringB22Test.tests
            JvmLoweringB23Test.tests
            JvmLoweringB24Test.tests
            JvmLoweringB25Test.tests
            JvmLoweringB26Test.tests
            JvmLoweringB27Test.tests
            JvmLoweringB28Test.tests
            JvmLoweringB29Test.tests
            JvmLoweringB30Test.tests
            JvmLoweringB31Test.tests
            JvmLoweringB32Test.tests
            JvmLoweringB33Test.tests
            JvmLoweringB34Test.tests
            JvmLoweringB35Test.tests
            JvmLoweringB36Test.tests
            JvmLoweringB37Test.tests
            JvmLoweringB38Test.tests
            JvmLoweringB39Test.tests
            JvmLoweringB40Test.tests
            JvmLoweringB41Test.tests
            JvmLoweringB42Test.tests
            JvmLoweringB43Test.tests
            JvmLoweringB44Test.tests
            JvmLoweringB45Test.tests
            JvmLoweringB46Test.tests
            JvmLoweringB47Test.tests
            JvmLoweringB48Test.tests
            JvmLoweringB49Test.tests
            JvmLoweringB50Test.tests
            JvmLoweringB51Test.tests
            JvmLoweringB52Test.tests
            JvmLoweringB53Test.tests
            JvmLoweringB54Test.tests
            JvmLoweringB55Test.tests
            JvmLoweringB56Test.tests
            JvmLoweringB57Test.tests
            JvmLoweringB58Test.tests
            JvmLoweringB59Test.tests
            JvmLoweringB60Test.tests
            JvmLoweringB61Test.tests
            JvmLoweringB62Test.tests
            JvmLoweringB63Test.tests
            JvmLoweringB64Test.tests
            JvmLoweringB65Test.tests
            JvmLoweringB66Test.tests
            JvmLoweringB67Test.tests
            JvmLoweringB68Test.tests
            JvmLoweringB69Test.tests
            JvmLoweringB70Test.tests
            JvmLoweringB71Test.tests
            JvmLoweringB72Test.tests
            JvmLoweringB73Test.tests
            JvmLoweringB74Test.tests
            JvmLoweringB75Test.tests
            JvmLoweringB76Test.tests
            JvmLoweringB77Test.tests
            JvmLoweringB78Test.tests
            JvmLoweringB79Test.tests
            JvmLoweringB80Test.tests
            JvmLoweringB81Test.tests
            JvmLoweringB82Test.tests
            JvmLoweringB83Test.tests
            JvmLoweringB84Test.tests
            JvmLoweringB85Test.tests
            JvmLoweringB86Test.tests
            JvmLoweringB87Test.tests
            JvmLoweringB88Test.tests
            JvmLoweringB89Test.tests
            JvmLoweringB90Test.tests
            JvmLoweringB91Test.tests
            JvmLoweringB92Test.tests
            JvmLoweringB93Test.tests
            JvmLoweringB94Test.tests
            JvmLoweringB95Test.tests
            JvmLoweringB96Test.tests
            JvmLoweringB97Test.tests
            JvmLoweringB98Test.tests
            JvmLoweringB99Test.tests
            JvmLoweringB100Test.tests
            JvmLoweringB101Test.tests
            JvmLoweringB102Test.tests
            JvmLoweringB103Test.tests
            JvmLoweringB104Test.tests
            JvmLoweringB105Test.tests
            JvmLoweringB106Test.tests
            JvmLoweringB107Test.tests
            JvmLoweringB108Test.tests
            JvmLoweringB109Test.tests
            JvmLoweringB110Test.tests
            JvmLoweringB111Test.tests
            JvmLoweringB112Test.tests
            JvmLoweringB113Test.tests
            JvmLoweringB114Test.tests
            JvmLoweringB115Test.tests
            JvmLoweringB116Test.tests
            JvmLoweringB117Test.tests
            JvmLoweringB118Test.tests
            JvmLoweringB119Test.tests
            JvmLoweringB120Test.tests
            JvmLoweringB121Test.tests
            JvmLoweringB122Test.tests
            JvmLoweringB123Test.tests
            JvmLoweringB124Test.tests
            JvmLoweringB125Test.tests
            JvmLoweringB126Test.tests
            JvmLoweringB127Test.tests
            JvmLoweringB128Test.tests
            JvmLoweringB129Test.tests
            JvmLoweringB130Test.tests
            JvmLoweringB131Test.tests
            JvmLoweringB132Test.tests
            JvmLoweringB133Test.tests
            JvmLoweringB134Test.tests
            SelfHostedLexerTests.tests
            SelfHostedParserTests.tests
            SelfHostedTypeCheckerTests.tests
            SelfHostedFmtTests.tests
            SelfHostedModeCheckerTests.tests
            SelfHostedContractElaboratorTests.tests
            SelfHostedTestSynthTests.tests
            SelfHostedManifestTests.tests
            SelfHostedVerifierTests.tests
            SelfHostedGeneratorTests.tests
            SelfHostedDerivesTests.tests
            MultiFilePackageTests.tests
            ProjectAsDllTests.tests
            CfgErasureTests.tests
            AspectWeaverTest.tests
        ]
    runTestsWithCLIArgs [] argv allTests
