#!/usr/bin/env python3
"""Helper for `scripts/audit-axioms.sh`.

Provides three modes:
  --table  REPO_ROOT                       — print the baseline section to stdout
  --update REPO_ROOT AUDIT_DOC             — rewrite §19 baseline section in place
  --check  REPO_ROOT AUDIT_DOC             — diff stored baseline vs current scan

Tracked alongside `docs/17-axiom-audit.md`; bump the audit doc via
`scripts/audit-axioms.sh --update` whenever a kernel @axiom is added,
removed, or reworded.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

BEGIN_MARK = "<!-- BEGIN AXIOM BASELINE -->"
END_MARK = "<!-- END AXIOM BASELINE -->"

DIRS = [
    ("dotnet", ("lyric-stdlib", "std", "_kernel")),
    ("jvm",    ("lyric-stdlib", "std", "_kernel_jvm")),
]


def find_axiom_strings(text: str) -> list[str]:
    """Yield each axiom argument with paren matching; tolerates multi-line.

    Only matches `@axiom(` annotations at column 0 of a line (skips
    `// see @axiom(...)` comment mentions).
    """
    out: list[str] = []
    i = 0
    while True:
        idx = text.find("@axiom(", i)
        if idx < 0:
            break
        line_start = text.rfind("\n", 0, idx) + 1
        prefix = text[line_start:idx]
        if prefix.strip() != "":
            i = idx + len("@axiom(")
            continue
        start = idx + len("@axiom(")
        depth = 1
        j = start
        in_str = False
        while j < len(text) and depth > 0:
            c = text[j]
            if c == '"' and (j == 0 or text[j - 1] != "\\"):
                in_str = not in_str
            elif not in_str:
                if c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
                    if depth == 0:
                        break
            j += 1
        inner = text[start:j].strip()
        if inner.startswith('"') and inner.endswith('"'):
            inner = inner[1:-1]
        inner = re.sub(r"\\\s*\n\s*", " ", inner)
        inner = re.sub(r"\s+", " ", inner).strip()
        out.append(inner)
        i = j + 1
    return out


def find_package(text: str) -> str:
    m = re.search(r"^package\s+([A-Za-z_][A-Za-z0-9_.]*)", text, re.M)
    return m.group(1) if m else "<unknown>"


def scan(repo_root: Path) -> list[tuple[str, str, str, str]]:
    records: list[tuple[str, str, str, str]] = []
    for platform, parts in DIRS:
        d = repo_root.joinpath(*parts)
        if not d.is_dir():
            continue
        for path in sorted(d.iterdir()):
            if path.suffix != ".l":
                continue
            text = path.read_text(encoding="utf-8")
            pkg = find_package(text)
            for ax in find_axiom_strings(text):
                records.append((platform, pkg, path.name, ax))
    return records


def render(records: list[tuple[str, str, str, str]]) -> str:
    lines: list[str] = [BEGIN_MARK, "", "| Platform | Package | File | Axiom |", "|---|---|---|---|"]
    for platform, pkg, fname, ax in records:
        # Escape `|` inside the axiom column (defensive; current axioms don't contain `|`).
        ax_safe = ax.replace("|", "\\|")
        lines.append(f"| `{platform}` | `{pkg}` | `{fname}` | {ax_safe} |")
    lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines) + "\n"


def update(audit_doc: Path, rendered: str) -> None:
    text = audit_doc.read_text(encoding="utf-8")
    i = text.find(BEGIN_MARK)
    j = text.find(END_MARK)
    if i >= 0 and j > i:
        j += len(END_MARK)
        # Keep one trailing newline.
        if j < len(text) and text[j] == "\n":
            j += 1
        new = text[:i] + rendered + text[j:]
    else:
        if not text.endswith("\n"):
            text += "\n"
        section = (
            "\n## 19. Machine-checked axiom baseline\n\n"
            "Regenerated by `scripts/audit-axioms.sh --update`.  CI fails "
            "whenever this baseline diverges from the actual `@axiom(...)` "
            "annotations in `lyric-stdlib/std/_kernel*/*.l`, so each "
            "production-side change must land in lockstep with this table.\n\n"
        )
        new = text + section + rendered
    audit_doc.write_text(new, encoding="utf-8")


def extract_stored_block(text: str) -> str | None:
    i = text.find(BEGIN_MARK)
    j = text.find(END_MARK)
    if i < 0 or j < 0 or j < i:
        return None
    j += len(END_MARK)
    if j < len(text) and text[j] == "\n":
        j += 1
    return text[i:j]


def cmd_table(repo_root: Path) -> int:
    records = scan(repo_root)
    sys.stdout.write(render(records))
    return 0


def cmd_update(repo_root: Path, audit_doc: Path) -> int:
    records = scan(repo_root)
    update(audit_doc, render(records))
    return 0


def cmd_check(repo_root: Path, audit_doc: Path) -> int:
    records = scan(repo_root)
    fresh = render(records)
    stored = extract_stored_block(audit_doc.read_text(encoding="utf-8"))
    if stored is None:
        sys.stderr.write(
            "::error::audit-axioms: BEGIN/END AXIOM BASELINE markers missing from "
            f"{audit_doc}\n  Run: scripts/audit-axioms.sh --update\n"
        )
        return 1
    if stored != fresh:
        import difflib

        sys.stderr.write(
            "::error::audit-axioms: docs/17-axiom-audit.md §19 baseline is out of "
            "sync with kernel files\n"
        )
        diff = difflib.unified_diff(
            stored.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile="docs/17 (stored)",
            tofile="kernel scan (fresh)",
        )
        for line in diff:
            sys.stderr.write("    " + line)
        sys.stderr.write("  Run: scripts/audit-axioms.sh --update\n")
        return 1
    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        sys.stderr.write(__doc__ or "")
        return 2
    mode = argv[1]
    repo_root = Path(argv[2])
    if mode == "--table":
        return cmd_table(repo_root)
    if mode == "--update":
        if len(argv) < 4:
            sys.stderr.write("missing AUDIT_DOC argument\n")
            return 2
        return cmd_update(repo_root, Path(argv[3]))
    if mode == "--check":
        if len(argv) < 4:
            sys.stderr.write("missing AUDIT_DOC argument\n")
            return 2
        return cmd_check(repo_root, Path(argv[3]))
    sys.stderr.write(f"unknown mode: {mode}\n")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
