#!/usr/bin/env python3
"""Embed lyric-compiler/lyric/wasm/glue_runtime.js in the compiler.

The module-shape JS glue's static half is a real .js file so it can be read,
linted and run under node directly; the compiler carries it as a string
constant in lyric-compiler/lyric/wasm_glue_runtime.l, which this script
regenerates.  `--check` exits non-zero when the committed .l file is stale
(CI runs it, so the two cannot drift).
"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "lyric-compiler", "lyric", "wasm", "glue_runtime.js")
DST = os.path.join(ROOT, "lyric-compiler", "lyric", "wasm_glue_runtime.l")


def render():
    js = open(SRC, encoding="utf-8").read()
    # Same delimiter rule as `lyric fmt` (fmt_core.l rawStringLit), so the
    # generated file is already in the formatter's canonical form.
    hashes = ""
    while '"' + hashes in js:
        hashes += "#"
    return (
        "//! Generated by scripts/gen_wasm_glue.py from wasm/glue_runtime.js. Do not edit.\n"
        "//!\n"
        "//! The static half of the `--shape module` JS glue (docs/35 W3).\n"
        "@pure\n"
        "package Lyric.WasmGlueRuntime\n"
        "\n"
        "pub func glueRuntimeJs(): String {\n"
        "  r" + hashes + '"' + js + '"' + hashes + "\n"
        "}\n"
    )


def main():
    out = render()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        have = open(DST, encoding="utf-8").read() if os.path.exists(DST) else ""
        if have != out:
            print("wasm_glue_runtime.l is stale: run scripts/gen_wasm_glue.py", file=sys.stderr)
            return 1
        return 0
    open(DST, "w", encoding="utf-8").write(out)
    return 0


sys.exit(main())
